[package]
name = "Lodestone"
version = "0.1.0"
edition = "2021"

exclude = [
    "target/*",
    "InstanceTest/*"
]

[[bin]]
name = "test_ground"
path = "src/test_ground/main.rs"

[[bin]]
name = "main"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { version = "0.5.13", features = ["headers", "ws"] }
axum-macros = "0.2.3"
futures = "0.3.21"
headers = "0.3"
tokio = { version = "1.0", features = ["full"] }
tokio-stream = "0.1"
tower-http = { version = "0.3.0", features = ["fs", "trace", "cors"] }
fancy-regex = "0.10.0"
argon2 = "0.4.1"
rand_core = { version = "0.6", features = ["std"] }
serde_json = "1.0.82"
serde = { version = "1.0", features = ["derive"] }

reqwest = { version = "0.11.10", features = ["stream", "blocking"] }
futures-util = "0.3.14"
indicatif = "0.15.0"

fs_extra = "1.2.0"

sanitize-filename = "0.4.0"
sysinfo = "0.26.2"
rlua = "0.19.1"
rand = "0.6.5"
log = "0.4.17"
env_logger = "0.9.0"
zip = "0.6.2"
async-trait = "0.1.56"
ts-rs = "6.1"
lazy_static = "1.4.0"
axum-auth = "0.2"
jsonwebtoken = "8.1.1"
chrono = "0.4.22"
ringbuffer = "0.8.5"
semver = {version="1.0", features = ["serde"]}
raw-cpuid = "10.6.0"
whoami = "1.2.3"
[dependencies.uuid]
version = "1.1.2"
features = [
    "serde",
    "v4",                # Lets you generate random UUIDs
    "fast-rng",          # Use a faster (but still sufficiently random) RNG
    "macro-diagnostics", # Enable better diagnostics for compile-time UUIDs
]